WIP - Issue 4956 - Implement search filter for country and state when editing an order
RenanLukas/woocommerce-android pull request #1
Opened 2021-11-07 20:20 UTC by RenanLukas

# Implement search for country/state on address editing screen

Closes: #4956

### Description
Implements a search feature for country and state selection on the address editing screen. Currently we have a Dialog for this selection, and user has to scroll to find the desired option. With the search filtering the items it is possible to find an option faster than scrolling.

### Testing instructions

1 - Login with an user that has at least one order of a physical product in any status (the order must contain a physical product in order to test all the scenarios);
2 - Navigate to "Orders" screen and tap on any order to open details;

**To test billing address**
3 - Tap on "Add Billing Address" or the edit button if the address is already filled.
4 - Tap on "Country"  to open search filter for country. Select a country;
5 - Tap on "State" to open search filter for state. Select a state;
6 - Tap on "Done" to update the address with the selected options.

**To test shipping address**
3 - Tap on "Add Shipping Address" or the edit button if the address is already filled.
4 - Tap on "Country"  to open search filter for country. Select a country;
5 - Tap on "State" to open search filter for state. Select a state;
6 - Tap on "Done" to update the address with the selected options.

### Images/gif

#### State disabled
![state_disabled](https://user-images.githubusercontent.com/14964993/140660246-e1a5b2d4-a6ee-4bbd-b734-ed45c7ae6a36.png)

#### Searching for country
![search_country](https://user-images.githubusercontent.com/14964993/140660250-0d1574a5-a414-491b-878f-3a07274f635d.png)

#### Search country with 3 results
![search_country_3_results](https://user-images.githubusercontent.com/14964993/140660257-7c4fef1d-ca3a-4dbd-9c98-b18acfce0aed.png)

#### Search country with 1 result
![searchh_country_1_result](https://user-images.githubusercontent.com/14964993/140660627-cf894448-fd77-4604-aacf-7c7f48fe1a8c.png)

#### Search empty state
![search_country_empty_state](https://user-images.githubusercontent.com/14964993/140660278-0a4b8187-7597-45e1-ad63-d741208a7e91.png)

#### Country selected
![search_country_selected](https://user-images.githubusercontent.com/14964993/140660299-5c99668a-3e4e-41ab-8352-6d7553faa5c3.png)

#### State enabled
![state_enabled](https://user-images.githubusercontent.com/14964993/140660309-c4c271be-7019-496b-94d0-5ec42c7443c4.png)

#### Search state
![search_state](https://user-images.githubusercontent.com/14964993/140660316-00d1eca6-bd90-4341-95bb-b83f5bce38d0.png)

#### Search state with 1 result
![search_state_1_result](https://user-images.githubusercontent.com/14964993/140660656-d1b6d844-0496-4918-8b01-04c17752480f.png)

#### Country and state selected
![country_state_selected](https://user-images.githubusercontent.com/14964993/140660330-d600925e-e06c-4861-ba1b-8a56e6a51e69.png)

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-11-08 19:03 UTC, nbradbury commented
Maybe consider using `android:imeOptions="flagNoExtractUi"` on the search view so the screen isn't taken over in landscape?

![land](https://user-images.githubusercontent.com/3903757/140802037-143e99b6-ca06-4167-8742-02c8442de10c.png)

2021-11-08 19:15 UTC, nbradbury commented
Minor nit: I realize the designs we shared with you came from iOS, but Material Guidelines recommend only capitalizing the first word, so this should be "Filter countries."

![filter](https://user-images.githubusercontent.com/3903757/140803404-2e8628bb-f41a-4356-a37d-b724308349a5.png)

2021-11-08 19:42 UTC, nbradbury commented
If I go to edit an address in the United States and no state has been selected, if I select one but then back out and discard changes, that state still gets saved to the address. A similar problem happens if you discard changes after selecting a different country.

I wasn't able to reproduce these in our `develop` so I'm assuming they were introduced in this PR?

2021-11-08 20:11 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/searchfilter/SearchFilterFragment.kt
> +        activity?.title = title
Just an FYI that you can override `getFragmentTitle()` in `BaseFragment` to supply the activity title, like this:

```
override fun getFragmentTitle() = navArgs.title
```

2021-11-08 21:12 UTC, nbradbury commented
@RenanLukas I've done my first round of reviews. You've done some very nice work here. I like the way you relied on `SearchFilterViewState` and made the filter screen so easy to reuse. 

I left a few comments for you to look into, but apart from the state/country reappearing there's nothing serious to address.

2021-11-09 23:23 UTC, RenanLukas commented
> Minor nit: I realize the designs we shared with you came from iOS, but Material Guidelines recommend only capitalizing the first word, so this should be "Filter countries."
> 
> ![filter](https://user-images.githubusercontent.com/3903757/140803404-2e8628bb-f41a-4356-a37d-b724308349a5.png)

@nbradbury Thanks for pointing out! 
Should we follow the same approach for the `Filter State / County` string? I've capitalized the words because that's how it looks like in the address edit screen. Would it make sense to change it to `Filter state / county` on the search filter screen and to `State / county` (instead of `State / County`) on the address edit screen?

2021-11-10 04:17 UTC, RenanLukas commented
@nbradbury thank you for taking the time to review my PR. I've left a [small question](https://github.com/RenanLukas/woocommerce-android/pull/1#issuecomment-964634986) and have addressed your comments on this first round.

![unit tests](https://user-images.githubusercontent.com/14964993/141048621-b6656682-2682-4ffd-8e2a-1d8b27400eb9.png)

2021-11-10 19:24 UTC, nbradbury commented
> Should we follow the same approach for the `Filter State / County` string? I've capitalized the words because that's how it looks like in the address edit screen.

@RenanLukas Looking at the iOS app I see it just says "State" (no county) so let's just mimic that in the address editing screen and the filter screens.

2021-11-10 19:38 UTC, nbradbury requested changes
@RenanLukas I'm looking at your PR and noticing that you missed a few comments I made (my mistake).

<img width="824" alt="Screen Shot 2021-11-10 at 2 37 36 PM" src="https://user-images.githubusercontent.com/3903757/141181632-506909b0-6bb2-4c01-9966-b6b444416e62.png">

2021-11-10 19:38 UTC, nbradbury commented on WooCommerce/src/main/res/layout/fragment_search_filter.xml
> +            app:layout_constraintEnd_toEndOf="parent"
Theses constraints are unnecessary since this is contained in a `FrameLayout`.

2021-11-10 19:38 UTC, nbradbury commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModelTest.kt
> +    fun `Should update viewState with selected country, reset selected state and enable state selection on onCountrySelected`() {
I'm getting a detekt `MaximumLineLength` error on this.

2021-11-10 19:38 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/searchfilter/SearchFilterAdapter.kt
> +        notifyDataSetChanged()
Would it make sense to use `DiffUtil.calculateDiff` here instead of `notifyDataSetChanged`?

2021-11-10 22:45 UTC, RenanLukas commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/searchfilter/SearchFilterAdapter.kt
> +        notifyDataSetChanged()
Makes sense 👍

2021-11-10 22:54 UTC, RenanLukas commented on WooCommerce/src/main/res/layout/fragment_search_filter.xml
> +            app:layout_constraintEnd_toEndOf="parent"
My bad 😅

2021-11-10 23:02 UTC, RenanLukas commented
Hey @nbradbury , thanks for checking it again. I've addressed the other comments you made.

2021-11-10 23:48 UTC, nbradbury approved these changes
Changes look great, very nice work! I'm going to ask Wojtek to give this a quick look and then I think we're good to merge 🎉

2021-11-11 03:39 UTC, wzieba reviewed
Hi @RenanLukas 👋  thanks for adding the feature, I've played with it and looks really nice. I left some ideas in comments, none of them is change request though - more like improvements suggestions.

I would ask you to work on one thing though: during testing I've spotted memory leaks. To reproduce it I opened country or state search fragment and returned to address editing fragment few times. Below I'm pasting leak canary report of one of the leaks. Could you please check what's the cause and fix it? Thanks!

```
​
┬───
│ GC Root: Global variable in native code
│
├─ android.graphics.animation.RenderNodeAnimator instance
│    Leaking: UNKNOWN
│    Retaining 437.5 kB in 7847 objects
│    ↓ RenderNodeAnimator.mTarget
│                         ~~~~~~~
├─ android.graphics.RenderNode instance
│    Leaking: UNKNOWN
│    Retaining 435.1 kB in 7769 objects
│    ↓ RenderNode.mAnimationHost
│                 ~~~~~~~~~~~~~~
├─ android.view.ViewAnimationHostBridge instance
│    Leaking: UNKNOWN
│    Retaining 435.0 kB in 7768 objects
│    ↓ ViewAnimationHostBridge.mView
│                              ~~~~~
├─ androidx.constraintlayout.widget.ConstraintLayout instance
│    Leaking: UNKNOWN
│    Retaining 435.0 kB in 7767 objects
│    View not part of a window view hierarchy
│    View.mAttachInfo is null (view detached)
│    View.mWindowAttachCount = 2
│    mContext instance of dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper, wrapping
│    activity com.woocommerce.android.ui.main.MainActivity with mDestroyed = false
│    ↓ View.mParent
│           ~~~~~~~
├─ androidx.recyclerview.widget.RecyclerView instance
│    Leaking: UNKNOWN
│    Retaining 374.6 kB in 6244 objects
│    View not part of a window view hierarchy
│    View.mAttachInfo is null (view detached)
│    View.mID = R.id.searchItemsList
│    View.mWindowAttachCount = 1
│    mContext instance of dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper, wrapping
│    activity com.woocommerce.android.ui.main.MainActivity with mDestroyed = false
│    ↓ RecyclerView.mAdapter
│                   ~~~~~~~~
├─ com.woocommerce.android.ui.searchfilter.SearchFilterAdapter instance
│    Leaking: UNKNOWN
│    Retaining 148 B in 7 objects
│    ↓ SearchFilterAdapter.onItemSelectedListener
│                          ~~~~~~~~~~~~~~~~~~~~~~
├─ com.woocommerce.android.ui.searchfilter.SearchFilterFragment$setupSearchList$1$1 instance
│    Leaking: UNKNOWN
│    Retaining 16 B in 1 objects
│    Anonymous subclass of kotlin.jvm.internal.Lambda
│    ↓ SearchFilterFragment$setupSearchList$1$1.this$0
│                                               ~~~~~~
╰→ com.woocommerce.android.ui.searchfilter.SearchFilterFragment instance
​     Leaking: YES (ObjectWatcher was watching this because com.woocommerce.android.ui.searchfilter.
​     SearchFilterFragment received Fragment#onDestroy() callback and Fragment#mFragmentManager is null)
​     Retaining 22.0 kB in 880 objects
​     key = 2bd9b70b-982e-4f0a-b9f5-747d6dff1c30
​     watchDurationMillis = 6413
​     retainedDurationMillis = 1404
​     componentContext instance of dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper,
​     wrapping activity com.woocommerce.android.ui.main.MainActivity with mDestroyed = false

METADATA

Build.VERSION.SDK_INT: 31
Build.MANUFACTURER: Google
LeakCanary version: 2.7
App process name: com.woocommerce.android.dev
Stats: LruCache[maxSize=3000,hits=11043,misses=210577,hitRate=4%]
RandomAccess[bytes=11356731,reads=210577,travel=119760579125,range=44441203,size=53458354]
Heap dump reason: user request
Analysis duration: 9520 ms
```

2021-11-11 03:39 UTC, wzieba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/searchfilter/SearchFilterAdapter.kt
> +) : RecyclerView.Adapter<SearchFilterViewHolder>() {
💡  If we use `DiffUtil`, maybe it makes sense to use [`ListAdapter`](https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter) class? It computes diff on background thread and make codebase consistent. We already use it in e.g. `ProductFilterOptionListAdapter`. WDYT?

2021-11-11 03:39 UTC, wzieba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/searchfilter/SearchFilterViewState.kt
> +sealed class SearchFilterViewState {
💯 nice! I like this interpretation.

2021-11-11 03:39 UTC, wzieba commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModelTest.kt
> +            verify(dataStore, times(1)).fetchCountriesAndStates(selectedSite.get())
⛏️  minor nitpick: `verify` by default checks for exactly 1 execution
```suggestion
            verify(dataStore).fetchCountriesAndStates(selectedSite.get())
```

2021-11-11 03:39 UTC, wzieba commented on WooCommerce/src/main/res/navigation/nav_graph_orders.xml
> +        tools:layout="@layout/fragment_search_filter">
💡 WDYT about adding some slide-in and slide-out animations?

2021-11-15 07:08 UTC, RenanLukas commented
Hey @wzieba , thank you very much for the review! I've addressed the improvement suggestions you made.

I'm having some trouble trying to reproduce the memory leak though. I've tried going back and forth multiple times between country/state search and address editing screen. I couldn't get anything on LeakCanary or memory profiler. Could it be that I'm not following the steps to reproduce correctly or maybe it's a flaky issue? 🤔 Either way I'll continue to try to reproduce it.

2021-11-15 19:44 UTC, wzieba commented
hi @RenanLukas , thank for adding improvements! About the leak, unfortunately I don't have precise steps but here I'm dropping a video that might help in reproduction:

https://user-images.githubusercontent.com/5845095/141843371-17c1ca74-3c23-4a62-970c-515f0baed2e2.mov

2021-11-16 04:58 UTC, RenanLukas commented
Thank you for recording a video @wzieba. It was really helpful 🎉 

Although I couldn't reproduce it on `LeakCanary`, this time I had more luck with the Memory Profiler. I've found a memory leak related to the search `TextWatcher` (it was never being removed 😬). After handling it, I didn't get any more leaks on Memory Profiler, but since I couldn't reproduce it on `LeakCanary`, could you please try to reproduce it again when you have time?

![leak_memory_profiler_2](https://user-images.githubusercontent.com/14964993/141923265-b94ef7dc-69a4-4bc7-a002-bdf0533e8424.png)

2021-11-17 21:07 UTC, wzieba commented
Thanks @RenanLukas , good job - I tried hard but couldn't reproduce the memory leak 🎉 .

---

I found one issue though: when we rotate screen, value of `Country` and `State` disappear. WDYT folks @nbradbury @RenanLukas  - should we fix that in scope of this PR or some next one?

https://user-images.githubusercontent.com/5845095/142282244-181406cc-c194-4b98-bdb0-b6014a900aa3.mov

2021-11-18 00:26 UTC, RenanLukas commented
Good catch @wzieba
A while ago I've tested the current version of this feature (with a Dialog instead of a Fragment) and the same thing happened.   
@nbradbury filed a bug [here](https://github.com/woocommerce/woocommerce-android/issues/5205). If any of you think it's worth to fix the bug in this PR, please let me know and I'll fix it.

https://user-images.githubusercontent.com/14964993/142308940-bbe686e4-f2c8-41a2-ae24-f8b5a39b8fcf.mp4

2021-11-18 02:00 UTC, wzieba commented
oh sorry, now I see the discussion on Slack. Sorry I missed that. I think it's completely fine to fix this in a separate PR.

Once again, great job on this PR!

2021-11-18 02:00 UTC, wzieba approved these changes

2021-11-18 05:38 UTC, RenanLukas commented
No worries @wzieba 
Thanks for the review 🎉 

@nbradbury @wzieba should I merge it?

2021-11-18 13:31 UTC, nbradbury commented
@RenanLukas You can merge it to your repo if you like, but we'll need to clone this PR and merge it to our repo since you don't have permission to do that.

2021-11-18 13:48 UTC, RenanLukas commented
@nbradbury right! I'll just merge to the feature branch on this repo then. Thanks!

2021-11-18 13:49 UTC, merged